-- Insert default roles if they don't exist
INSERT INTO roles (name) 
SELECT 'ROLE_USER'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_USER');

INSERT INTO roles (name)
SELECT 'ROLE_ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_ADMIN');

INSERT INTO roles (name)
SELECT 'ROLE_DEPARTMENT'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_DEPARTMENT');
